version: "3.7"

services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    networks:
      - traefik_webgateway
      - private
    labels:
      - traefik.enable=true
      - traefik.http.services.open-webui.loadbalancer.server.port=8080
      - traefik.http.routers.open-webui.rule=Host(`${OPEN_WEBUI_DOMAIN}`)
      - traefik.http.routers.open-webui.entrypoints=web
      # https
      - traefik.http.middlewares.open-webui-redirect-websecure.redirectscheme.scheme=https
      - traefik.http.routers.open-webui.middlewares=open-webui-redirect-websecure
      - traefik.http.routers.open-webui-websecure.rule=Host(`${OPEN_WEBUI_DOMAIN}`)
      - traefik.http.routers.open-webui-websecure.tls=true
      - traefik.http.routers.open-webui-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.open-webui-websecure.entrypoints=websecure

networks:
  traefik_webgateway:
    external: true
  private:
    driver: bridge

volumes:
  open-webui:
  # Odkomentuj poniższe, jeśli używasz Ollama
  # ollama: